version: 1.0.0a{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
build:
  project: newsmake.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: rRIkulSt7z29rQNy3Nw+l8yhKBFnuMww+vyHHuBZwQICQMdhUggcYP7ofbpty3dc
  on:
    APPVEYOR_REPO_TAG: true