version: 1.0.4a{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
install:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019 Preview")

    {

    Write-Host "Installing .NET Core 5.0.100-preview.4.20202.8 SDK..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-sdk-5.0.100-preview.4.20202.8-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.4.20202.8/dotnet-sdk-5.0.100-preview.4.20202.8-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Framework 4.8 Targeting Pack..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\ndp48-devpack-enu.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/9854b5f2-2341-4136-ad7d-1d881ab8d603/e3a011f2a41a59b086f78d64e1c7a3fc/ndp48-devpack-enu.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green

    }
before_build:
- ps: >-
    nuget restore

    dotnet build

    dotnet pack --configuration Release --include-symbols --no-build
test_script:
- ps: >-
    dotnet tool install --global newsmake --add-source "./bin/Any CPU/Release/"

    newsmake build
artifacts:
- path: '**\*.nupkg'
  name: myartifact
deploy:
- provider: NuGet
  api_key:
    secure: Mrzgs3GkYupK8M/4ZfFdjYR32bbkMWCsgzdL9fD/tfnSCOw4tzzmSUGj7mmm5ssV
  artifact: myartifact
  on:
    APPVEYOR_REPO_TAG: true
