version: 1.0.4a{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    nuget restore

    dotnet build

    dotnet pack --configuration Release --include-symbols --no-build
test_script:
- ps: >-
    dotnet tool install --global newsmake --add-source "./bin/Any CPU/Release/"

    newsmake
artifacts:
- path: '**\*.nupkg'
  name: myartifact
deploy:
- provider: NuGet
  api_key:
    secure: rRIkulSt7z29rQNy3Nw+l8yhKBFnuMww+vyHHuBZwQICQMdhUggcYP7ofbpty3dc
  artifact: myartifact
  on:
    APPVEYOR_REPO_TAG: true