version: 1.0.4a{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
install:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019 Preview")

    {

    Write-Host "Installing .NET Core 3.0.100-preview5-011568 SDK..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-sdk-3.0.100-preview5-011568-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/c2521385-1648-415f-8503-b1860b80d57b/5d571a80ed7ba1cb5a085d28c8a018bf/dotnet-sdk-3.0.100-preview5-011568-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Core 3.0.0-preview5-27626-15 runtime..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\dotnet-runtime-3.0.0-preview5-27626-15-win-x64.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/d7af8514-482d-4fde-acfc-695fbffd320a/a575c0764cce6ca7ea982eb36a90695f/dotnet-runtime-3.0.0-preview5-27626-15-win-x64.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green


    Write-Host "Installing .NET Framework 4.8 Targeting Pack..." -ForegroundColor Cyan

    Write-Host "Downloading..."

    $exePath = "$env:TEMP\ndp48-devpack-enu.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/9854b5f2-2341-4136-ad7d-1d881ab8d603/e3a011f2a41a59b086f78d64e1c7a3fc/ndp48-devpack-enu.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait "$exePath" /quiet /norestart

    del $exePath

    Write-Host "Installed" -ForegroundColor Green

    }
before_build:
- ps: >-
    nuget sources Add -Name "Generic Roslyn Analyzers" -Source https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json

    nuget restore

    dotnet build

    dotnet pack --configuration Release --include-symbols --no-build
test_script:
- ps: >-
    dotnet tool install --global newsmake --add-source "./bin/Any CPU/Release/"

    newsmake build
artifacts:
- path: '**\*.nupkg'
  name: myartifact
deploy:
- provider: NuGet
  api_key:
    secure: rRIkulSt7z29rQNy3Nw+l8yhKBFnuMww+vyHHuBZwQICQMdhUggcYP7ofbpty3dc
  artifact: myartifact
  on:
    APPVEYOR_REPO_TAG: true
