name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.4.20202.8
    - name: Build with dotnet
      run: dotnet build --configuration Release
